[display]
width = 1920
height = 1080

[camera]
fov = 80.0
near = 0.1
far = 1000.0

[input]
sensitivity = 0.6
move_speed = 20.0

[targets]
color = [255, 0, 255] # R, G, B
sphere_detail = 8

[environment]
light_direction = [0.5, 2.0, -1.5]
scene_color = [55, 55, 55]

[crosshair]
color = 0xFF00FF00
line_length = 3
line_thickness = 2
gap = 0